package com.necro.raid.dens.common.items;

import net.minecraft.core.Holder;
import net.minecraft.world.item.Item;

public class ModItems {
    public static Holder<Item> RAID_POUCH;
    public static Holder<Item> ATTACK_CHEER;
    public static Holder<Item> DEFENSE_CHEER;
    public static Holder<Item> HEAL_CHEER;
    public static Holder<Item> RAID_SHARD;
    public static Holder<Item> CATCHING_CHARM;
    public static Holder<Item> ARTIFICIAL_CHARM;
    public static Holder<Item> BLUE_EON_CHARM;
    public static Holder<Item> BLUE_WARRIOR_CHARM;
    public static Holder<Item> BOUNDARY_CHARM;
    public static Holder<Item> CONTINENT_CHARM;
    public static Holder<Item> DEEP_BLACK_CHARM;
    public static Holder<Item> DJINN_CHARM;
    public static Holder<Item> FUSED_BLACK_CHARM;
    public static Holder<Item> FUSED_WHITE_CHARM;
    public static Holder<Item> GENETIC_CHARM;
    public static Holder<Item> HIGH_KING_CHARM;
    public static Holder<Item> JEWEL_CHARM;
    public static Holder<Item> KING_CHARM;
    public static Holder<Item> LAVA_CHARM;
    public static Holder<Item> MOON_CHARM;
    public static Holder<Item> ORDER_CHARM;
    public static Holder<Item> PITCH_BLACK_CHARM;
    public static Holder<Item> PRISM_CHARM;
    public static Holder<Item> PRISMATIC_DAWN_CHARM;
    public static Holder<Item> PRISMATIC_DUSK_CHARM;
    public static Holder<Item> RED_EON_CHARM;
    public static Holder<Item> RED_WARRIOR_CHARM;
    public static Holder<Item> SEA_BASIN_CHARM;
    public static Holder<Item> SKY_HIGH_CHARM;
    public static Holder<Item> STEED_CHARM;
    public static Holder<Item> SUN_CHARM;
    public static Holder<Item> THUNDERCLAP_CHARM;
    public static Holder<Item> VAST_WHITE_CHARM;
    public static Holder<Item> ZENITH_CHARM;
    public static Holder<Item> INCARNATE_CHARM;
    public static Holder<Item> ABUNDANCE_CHARM;
    public static Holder<Item> ROCK_PEAK_CHARM;
    public static Holder<Item> ICEBERG_CHARM;
    public static Holder<Item> IRON_CHARM;
    public static Holder<Item> ELECTRON_CHARM;
    public static Holder<Item> DRAGON_ORB_CHARM;
    public static Holder<Item> COLOSSAL_CHARM;
    public static Holder<Item> MUSIC_DISC_AREA_ZERO;
    public static Holder<Item> MUSIC_DISC_CANALAVE;
    public static Holder<Item> MUSIC_DISC_CORONET;
    public static Holder<Item> MUSIC_DISC_ECRUTEAK;
    public static Holder<Item> MUSIC_DISC_GREAT_CANYON;
    public static Holder<Item> MUSIC_DISC_HEARTWOOD;
    public static Holder<Item> MUSIC_DISC_LAKES;
    public static Holder<Item> MUSIC_DISC_MT_PYRE;
    public static Holder<Item> MUSIC_DISC_OBSIDIAN_FIELDLANDS;
    public static Holder<Item> MUSIC_DISC_ORAS_SURF;
    public static Holder<Item> MUSIC_DISC_POKEMON_LEAGUE_NIGHT;
    public static Holder<Item> MUSIC_DISC_ROUTE_216;
}
