plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

loom {
    enableTransitiveAccessWideners.set(true)
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

repositories {
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    mavenCentral()
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"
    modImplementation "net.fabricmc:fabric-language-kotlin:$rootProject.fabric_kotlin"
    modImplementation "com.cobblemon:fabric:$rootProject.cobblemon_version"
    modImplementation "software.bernie.geckolib:geckolib-fabric-$rootProject.geckolib_version"
    include(modApi "me.shedaniel.cloth:cloth-config-fabric:$rootProject.cloth_config_version")

    modImplementation "com.terraformersmc:modmenu:11.0.3"
    modRuntimeOnly "maven.modrinth:jade:$rootProject.jade_version+fabric"
    // modRuntimeOnly "lol.bai:badpackets:fabric-$rootProject.badpackets_version"
    modCompileOnly "mcp.mobius.waila:wthit:fabric-$rootProject.wthit_version"

    modImplementation "curse.maven:cobbledollars-859232:6604561"
    modImplementation "curse.maven:radical-cobblemon-trainers-api-1152792:7257754"

    modRuntimeOnly "io.wispforest:accessories-fabric:1.1.0-beta.52+1.21.1"
    modImplementation "curse.maven:cobblemon-mega-showdown-1189523:7833505"
    modRuntimeOnly "maven.modrinth:supermartijn642s-config-lib:1.1.8-fabric-mc1.21"
    modRuntimeOnly "dev.architectury:architectury-fabric:13.0.8"

    modRuntimeOnly "curse.maven:cobblemon-shadowed-hearts-1438842:7577271"
    modRuntimeOnly "curse.maven:special-model-loader-782421:5744313"
    modRuntimeOnly "curse.maven:forge-config-api-port-547434:7213608"
    runtimeOnly "com.electronwill.night-config:core:3.8.4"
    runtimeOnly "com.electronwill.night-config:toml:3.8.4"
    runtimeOnly "de.javagl:obj:0.4.0"
    runtimeOnly "org.xerial:sqlite-jdbc:3.53.0.0"

    modCompileOnly "mezz.jei:jei-1.21.1-fabric-api:19.27.0.340"
    modRuntimeOnly "mezz.jei:jei-1.21.1-fabric:19.27.0.340"

    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:16.0.799"
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:16.0.799"
    // modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:16.0.799"

    modCompileOnly "dev.emi:emi-fabric:1.1.22+1.21.1:api"
    // modRuntimeOnly "dev.emi:emi-fabric:1.1.22+1.21.1"

    modCompileOnly "maven.modrinth:navas-zamega:x5u68zHH"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    var replaceProperties = [
        display_name: rootProject.display_name,
        description: rootProject.mod_description,
        archives_name: rootProject.archives_name,
        version: project.version,
        minecraft_version: rootProject.minecraft_version,
        cobblemon_version: rootProject.cobblemon_dependency,
        geckolib_version: rootProject.geckolib_dependency
    ]
    inputs.properties replaceProperties

    filesMatching('fabric.mod.json') {
        expand  replaceProperties
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    injectAccessWidener = true
    inputFile.set shadowJar.archiveFile
}