architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/cobblemonraiddens.accesswidener")
}

repositories {
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "com.cobblemon:mod:$rootProject.cobblemon_version"
    modCompileOnly "com.cobblemon:mod:1.7.2+1.21.1"
    implementation(files "libs/molang-1.1.19.jar")
    modCompileOnly "com.terraformersmc:modmenu:11.0.3"
    modCompileOnly "maven.modrinth:jade:$rootProject.jade_version+neoforge"
    modCompileOnly "mcp.mobius.waila:wthit-api:mojmap-$rootProject.wthit_version"
    modImplementation "software.bernie.geckolib:geckolib-common-$rootProject.geckolib_version"
    modCompileOnly(files "libs/CobblemonSizeVariationFabric-1.4.0+1.7.0.jar")
    modCompileOnly "curse.maven:irisshaders-455508:6213635"

    modCompileOnly "curse.maven:cobbledollars-859232:6604561"
    modCompileOnly "curse.maven:radical-cobblemon-trainers-api-1152792:7257752"
    modCompileOnly "curse.maven:cobblemon-vocalized-1476578:7710117"

    modRuntimeOnly "io.wispforest:accessories-common:1.1.0-beta.52+1.21.1"
    modCompileOnly "curse.maven:cobblemon-mega-showdown-1189523:7833505"
    modCompileOnly "dev.architectury:architectury:13.0.8"

    modCompileOnly "curse.maven:cobblemon-shadowed-hearts-1438842:7577271"

    modCompileOnly "mezz.jei:jei-1.21.1-common-api:19.27.0.340"

    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api:16.0.799"
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin:16.0.799"

    modCompileOnly "maven.modrinth:navas-zamega:x5u68zHH"
    modCompileOnly "maven.modrinth:simpletms-tms-and-trs-for-cobblemon:uWiIETYV"

    compileOnly "dev.emi:emi-xplat-mojmap:1.1.22+1.21.1:api"

    include(modApi "me.shedaniel.cloth:cloth-config:$rootProject.cloth_config_version")
}

sourceSets {
    main {
        resources.srcDir "src/main/generated"
        resources.exclude ".cache"
    }
}